name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python:
    name: Python Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: extractions/setup-just@v1

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ['3.9', '3.10']
          cache: 'poetry'

      - run: poetry install

      - run: |
          poetry run mypy --install-types -m extism --non-interactive

      - name: Run Python lint
        run: |
          just lint

      - name: Run Python tests
        run: |
          just test

      - name: Run Python docs
        run: |
          just docs
